name: tets workflow
on: workflow_dispatch
jobs:
  tets-job:
    runs-on: ubuntu-latest
    steps: 
      - name: print
        run: |
          echo " this is a test"
          echo " this is a test 2"

      - name: print two
        run: echo "this is a test two"
